name: Release
on:
  push:
    # branches:
    #   - dev
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install gettext
          python -m pip install -U pip build

      - name: Generate final distribution
        run: python -m build

      - name: Upload source distribution as an action artifact
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/stmaterial-*.tar.gz
      - name: Upload wheel distribution as an action artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/stmaterial-*-py3-none-any.whl

      - name: Make a GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
